const { Schema, model } = require('mongoose');
const config = require("../nodedetails/config");

const releaseOrderSchema = new Schema({

  roNumber: { type: Number, default: 0 },
  // newsPaperName: { type: Schema.Types.ObjectId, ref: 'NewsPaper', required: true },
  // newsPaperCenter: { type: Schema.Types.ObjectId, ref: 'NewsPaperCenter', required: true },
  roDate: { type: Date, default: new Date() },
  newsPaperName: { type:String, required: true },
  newsPaperCenter: { type:String, required: true },
  typeClientNameHere: { type: String, required: true },
  subAgent: { type: String, required: true },
  // advtEditionType: { type: Schema.Types.ObjectId, ref: 'adsEditionSchema', required: true },
  // advtType: { type: Schema.Types.ObjectId, ref: 'advtEditionSchema', required: true },
  advtEditionType: { type: String, required: true },
  advtType: { type: String,  required: true },
  displayAdvtType: { type: Boolean, default: false },
  editionsYouSelected: [{ type: String, default: "" }],
  poNumber: { type: String, default: "" },
  invoiceEditionName: { type: String, default: "" },
  invoiceEditionArea: { type: String, default: "" },
  roInsertionDate: { type: String, default: "" },
  heightInCM: { type: Number, default: "" },
  widthInCM: { type: Number, default: "" },
  sqCM: { type: Number, default: "" },
  flatRateMedia: { type: Boolean, default: false },
  mediaRatePerSqCM: { type: String, default: "" },
  flatRateClient: { type: Boolean, default: false },
  clientRatePerSqCM: { type: String, default: "" },
  advertisementCaption: { type: String, default: "" },
  byEmail: { type: String, default: "" },
  //prevSentMaterial: { type: Schema.Types.ObjectId, ref: 'dataSourceSchema', required: true},
  // advtIssueOrMalarOrOthers: { type: Schema.Types.ObjectId, ref: 'issueSchema', required: true },
  // malarType: { type: Schema.Types.ObjectId, ref: 'issueSubCatSchema', required: true },
  // advtHue: { type: Schema.Types.ObjectId, ref: 'hueSchema', required: true },
  advtIssueOrMalarOrOthers: { type:String,  required: true },
  malarType: { type:String,  required: true },
  advtHue: { type:String,  required: true },
  advtHuePercentage: { type: String, default: "" },
  advtHueMediaAmount: { type: Number, default: 0 },
  advtHueClientAmount: { type: Number, default: 0 },
  advtHueTotal: { type: Number, default: 0 },
  advtHuePageNo: { type: Number, default: 0 },
  //advtPosition: { type: Schema.Types.ObjectId, ref: 'advtPositionSchema', required: true },
  advtPosition: { type: String, required: true },
  advtPositionPercentage: { type: String, default: "" },
  advtPositionMediaAmount: { type: Number, default: 0 },
  advtPositionClientAmount: { type: Number, default: 0 },
  advtPositionTotal: { type: Number, default: 0 },
  advtClientPosition: { type: String, default: "" },
  paperCopies: { type: Number, default: 0 },
  //scheme: { type: Schema.Types.ObjectId, ref: 'schemaModel' },
  scheme: { type:String },
  extra: { type: String, default: "" },
  specialInstructions1: { type: String, default: "" },
  specialInstructions2: { type: String, default: "" },

  specialDiscount: {
    percentage:{ type: String, default: "" },
    mediaAmount: { type: Number, default: 0 },
    clientAmount: { type: Number, default: 0 },
    discount: { type: Number, default: 0 },
    // discountCategory: { type: Schema.Types.ObjectId, ref: 'DiscountCategory', default: null },
    // noticeType: { type: Schema.Types.ObjectId, ref: 'NoticeType', default: null },
    discountCategory: { type: String, default: null },
    noticeType: { type: String, default: null },
  },
  clientDiscount: {
    percentage:{ type: String, default: "" },
    amount: { type: Number, default: 0 },
    discount: { type: Number, default: 0 },
    advertisementCoordinator: { type: String, default: "" },
  },
  remindForNextYear: { type: Boolean, default: false },
  //selectedGST: { type: Schema.Types.ObjectId, ref: 'GST', default: null },
  selectedGST: { type:String, default: null },
  clientApprovalRate: { type: String, default: 0 },
  releaseDate: [{ type: Date, default: null }],
  isReleased:  { type: Boolean, default: false },
  isCancelled: { type: Boolean, default: false },
  isShifted: { type: Boolean, default: false },
  validity: { type: Date, default: new Date() },
  freeAds: { type: Number, default: 0 },
  totalGST: { type: Number, default: 0 },
  totalWithGST: { type: Number, default: 0 },
  isRoGenerated: { type: Boolean, default: false },
  roUrl: { type: String, default: null },
  isClientRoGenerated: { type: Boolean, default: false },
  isVendorRoGenerated: { type: Boolean, default: false },
  clientRoUrl: { type: String, default: null },
  vendorRoUrl: { type: String, default: null },
  vendorId: { type: String },
  
}, { versionKey: false, timestamps: true })

module.exports = model('ReleaseOrderOfNewspaper', releaseOrderSchema, config.dbPrefix + 'REPAPSWENFOREDROESAELER')